export const COUNTRIES = [
  { country: "Afghanistan", currency: "AFN" },
  { country: "Albania", currency: "ALL" },
  { country: "Algeria", currency: "DZD" },
  { country: "Angola", currency: "AOA" },
  { country: "Antigua and Barbuda", currency: "XCD" },
  { country: "Argentina", currency: "ARS" },
  { country: "Armenia", currency: "AMD" },
  { country: "Australia", currency: "AUD" },
  { country: "Azerbaijan", currency: "AZN" },
  { country: "Bahamas", currency: "BSD" },
  { country: "Bahrain", currency: "BHD" },
  { country: "Bangladesh", currency: "BDT" },
  { country: "Barbados", currency: "BBD" },
  { country: "Belarus", currency: "BYN" },
  { country: "Botswana", currency: "BWP" },
  { country: "Brazil", currency: "BRL" },
  { country: "Brunei", currency: "BND" },
  { country: "Cambodia", currency: "KHR" },
  { country: "Cameroon", currency: "XAF" },
  { country: "Canada", currency: "CAD" },
  { country: "Cape Verde", currency: "CVE" },
  { country: "China", currency: "CNY" },
  { country: "Colombia", currency: "COP" },
  { country: "Comoros", currency: "KMF" },
  { country: "Costa Rica", currency: "CRC" },
  { country: "Croatia", currency: "EUR" },
  { country: "Cuba", currency: "CUP" },
  { country: "Egypt", currency: "EGP" },
  { country: "Gambia", currency: "GMD" },
  { country: "Georgia", currency: "GEL" },
  { country: "Ghana", currency: "GHS" },
  { country: "India", currency: "INR" },
  { country: "Indonesia", currency: "IDR" },
  { country: "Iraq", currency: "IQD" },
  { country: "Japan", currency: "JPY" },
  { country: "Jordan", currency: "JOD" },
  { country: "Kazakhstan", currency: "KZT" },
  { country: "Kenya", currency: "KES" },
  { country: "Korea, North", currency: "KPW" },
  { country: "Korea, South", currency: "KRW" },
  { country: "Kuwait", currency: "KWD" },
  { country: "Libya", currency: "LYD" },
  { country: "Mexico", currency: "MXN" },
  { country: "Norway", currency: "NOK" },
  { country: "Oman", currency: "OMR" },
  { country: "Pakistan", currency: "PKR" },
  { country: "Palestine", currency: "ILS" },
  { country: "Panama", currency: "PAB" },
  { country: "Papua New Guinea", currency: "PGK" },
  { country: "Paraguay", currency: "PYG" },
  { country: "Peru", currency: "PEN" },
  { country: "Philippines", currency: "PHP" },
  { country: "Poland", currency: "PLN" },
  { country: "Qatar", currency: "QAR" },
  { country: "Romania", currency: "RON" },
  { country: "Russia", currency: "RUB" },
  { country: "Serbia", currency: "RSD" },
  { country: "Seychelles", currency: "SCR" },
  { country: "Sierra Leone", currency: "SLL" },
  { country: "Singapore", currency: "SGD" },
  { country: "South Africa", currency: "ZAR" },
  { country: "South Sudan", currency: "SSP" },
  { country: "Sri Lanka", currency: "LKR" },
  { country: "Sudan", currency: "SDG" },
  { country: "Suriname", currency: "SRD" },
  { country: "Sweden", currency: "SEK" },
  { country: "Switzerland", currency: "CHF" },
  { country: "Syria", currency: "SYP" },
  { country: "Togo", currency: "XOF" },
  { country: "Tonga", currency: "TOP" },
  { country: "Trinidad and Tobago", currency: "TTD" },
  { country: "Tunisia", currency: "TND" },
  { country: "Turkey", currency: "TRY" },
  { country: "Turkmenistan", currency: "TMT" },
  { country: "Uganda", currency: "UGX" },
  { country: "Ukraine", currency: "UAH" },
  { country: "United Arab Emirates", currency: "AED" },
  { country: "United Kingdom", currency: "GBP" },
  { country: "United States", currency: "USD" },
];
